config/routes.rb
Readonce::Application.routes.draw do
  devise_for :users
  resource :mockup, controller: 'mockup', only: [:index, :show]
  
  root to: 'mockup#index'
  
  resources :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
  
  validates :body, presence: true
  validates :receiver_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :messages, foreign_key: :sender_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  
  respond_to :html
  
  def index
  end
  
  def new
  end
  
  def create
    @message = current_user.messages.create(message_params)
    respond_with message, location: messages_url
  end
  
  private
  
  def message_params
    params[:message].permit :body, :receiver_id
  end
  
  def message
    @message ||= Message.new
  end
  helper_method :message
  
  def messages
    @messages ||= current_user.messages
  end
  helper_method :messages
  
  def receivers
    @receivers ||= User.all
  end
  helper_method :receivers
  
end

app/controllers/mockup_controller.rb
class MockupController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/mockup_helper.rb
module MockupHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Readonce</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/index.html.erb
<div class='container'>
  <div id='messages'>
    <h1>Messages</h1>

    <% messages.each do |message| %>
      <div class='message'>
        <span class='message-sender'><%= message.sender.email %></span>
        <time><%= time_ago_in_words message.created_at %></time>
        <span class='message-excerpt'><%= link_to truncate(message.body), message_path(message) %></span>
      </div>
    <% end %>
    
  </div>
</div>

app/views/messages/new.html.erb
<%= form_for message do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(message.errors.count, "error") %> 
        prohibited this message from being saved:
      </h2>
      <ul>
        <% message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.label :receiver_id, 'Receiver' %>
<%= f.collection_select :receiver_id, receivers, :id, :email, include_blank: true %>
  <%= f.submit 'Send' %>
<% end %>

app/views/mockup/index.html.erb
<div class='container'>
  <div id='messages'>
    <h1>Messages</h1>
    <% 2.times do %>
      <div class='message'>
        <span class='message-sender'>Ben</span>
        <time>5 minutes ago</time>
        <span class='message-excerpt'><%= link_to "Hey. I saw this and thought you'd find it funny...", mockup_path %></span>
      </div>
    <% end %>
    <div class='message read'>
      <span class='message-sender'>Ben</span>
      <time>5 minutes ago</time>
      <span class='message-excerpt'>Hey. I saw this and thought you'd find it funny...</span>
    </div>
    <% 5.times do %>
      <div class='message'>
        <span class='message-sender'>Ben</span>
        <time>5 minutes ago</time>
        <span class='message-excerpt'><%= link_to "Hey. I saw this and thought you'd find it funny...", mockup_path %></span>
      </div>
    <% end %>
  </div>
</div>

app/views/mockup/show.html.erb
<div class='container'>
  <article id='message-single'>
    <header>
      <span class='message-sender'>Ben</span>
      <time>5 minutes ago</time>
    </header>
    
    <p>
      Aesthetic sustainable salvia banh mi exercitation proident. 
      Viral incididunt actually, aesthetic anim dolor selfies 
      dolore literally Truffaut. Farm-to-table Banksy nulla Austin, 
      aesthetic photo booth kogi XOXO synth yr pariatur Carles 
      keffiyeh tousled fingerstache. Anim paleo plaid do, deep v 
      XOXO meggings forage. Four loko banh mi farm-to-table, pop-up 
      plaid church-key Wes Anderson nihil McSweeney's American Apparel 
      ugh mlkshk. Fingerstache commodo master cleanse adipisicing, 
      small batch keytar sed eiusmod. Voluptate ut non fixie bitters, 
      tofu Carles do brunch forage elit excepteur mlkshk.
    </p>

    <p>
      Food truck seitan est whatever farm-to-table, chillwave pop-up 
      laborum ullamco sed swag selfies kogi roof party mlkshk. XOXO 
      master cleanse Godard Pinterest PBR&B irony, swag organic Terry 
      Richardson culpa tattooed +1 exercitation. Gluten-free eu consectetur 
      nesciunt, Banksy Williamsburg cred dolor culpa stumptown distillery. 
      Bitters bicycle rights nihil, quis seitan 8-bit Intelligentsia 
      dreamcatcher cornhole plaid ad direct trade. Tempor Pinterest 
      reprehenderit whatever, 3 wolf moon kogi irure post-ironic church-key. 
      Anim small batch XOXO, sustainable elit umami officia four loko 
      laboris reprehenderit ennui twee jean shorts irure Blue Bottle. Deep 
      v PBR&B proident small batch ad.
    </p>
  </div>
</div>